// getFormConfig.tsx

import React from 'react';
import LocalPhoneIcon from '@mui/icons-material/LocalPhone';
import EmailIcon from '@mui/icons-material/Email';
import HomeIcon from '@mui/icons-material/Home';
import BusinessIcon from '@mui/icons-material/Business';
import { FormConfig } from '../interfaces';
import { DataLists } from '../interfaces';

import { createMirrorHandler } from './helpers';

export function getFormConfig({ paymentMethods, shippingMethods, sellers }: DataLists): FormConfig {
  const formConfig: FormConfig = {
    basic: {
      title: "Datos Básicos",
      fields: {
        name: {
          label: "Nombre",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          width: 4,
        },
        lastName: {
          label: "Apellido",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          width: 4,
        },
        id: {
          label: "CI",
          errorCheck: (value) => /^(?:[VEJ]-?)?\d{7,8}$/.test(value),
          helperText: "ej: V12345679 ó 12345678",
          width: 4,
        },
        phone: {
          label: "Teléfono",
          errorCheck: (value) => /^[0-9]{10,14}$/.test(value),
          helperText: "ej: 584141234567 ó +584141234567 ó 04143201028",
          adornment: <LocalPhoneIcon color="secondary" />,
        },
        email: {
          label: "Correo",
          errorCheck: (value) => /\S+@\S+\.\S+/.test(value),
          helperText: "Formato no válido.",
          adornment: <EmailIcon color="secondary" />,
        },
        line1: {
          label: "Dirección (Linea 1)",
          errorCheck: (value) => value?.length >= 20,
          helperText: "Incluir todos los detalles posibles, incluidas referencias.",
          minRows: 3,
          adornment: <HomeIcon color="secondary" />,
          width: 12,
        },
        line2: {
          label: "Dirección (Linea 2)",
          errorCheck: (value) => value?.length >= 20,
          helperText: "Incluir todos los detalles posibles, incluidas referencias.",
          minRows: 3,
          adornment: <HomeIcon color="secondary" />,
          width: 12,
        },
        city: {
          label: "Ciudad",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          width: 4,
        },
        state: {
          label: "Estado",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          width: 4,
        },
        country: {
          label: "País",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          width: 4,
        },
        zipCode: {
          label: "Código Postal",
          errorCheck: (value) => /^\d{5}$/.test(value),
          helperText: "Formato no válido.",
          width: 4,
        },
        reference: {
          label: "Referencia",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          width: 4,
        },
      },
      actionType: "SET_CONSUMER_BASIC",
    },
    shipping: {
      title: "Datos de Envío",
      fieldsTitle: "Dirección de Envío",
      fields: {
        shippingEqualsBasic: {
          label: "Igual a datos básicos",
          type: "checkbox",
          defaultValue: true,
          width: 12,
        },
        name: {
          label: "Nombre",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          width: 4,
          conditionedBy: "shipping.shippingEqualsBasic",
          onConditionChange: createMirrorHandler("shipping.name", "basic.name"),
        },
        lastName: {
          label: "Apellido",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          width: 4,
          conditionedBy: "shipping.shippingEqualsBasic",
          onConditionChange: createMirrorHandler("shipping.lastName", "basic.lastName"),
        },
        email: {
          label: "Correo",
          errorCheck: (value) => /\S+@\S+\.\S+/.test(value),
          helperText: "Formato no válido.",
          adornment: <EmailIcon color="secondary" />,
          conditionedBy: "shipping.shippingEqualsBasic",
          onConditionChange: createMirrorHandler("shipping.email", "basic.email"),
        },
        phone: {
          label: "Teléfono",
          errorCheck: (value) => /^[0-9]{10,14}$/.test(value),
          helperText: "ej: 584141234567 ó +584141234567 ó 04143201028",
          adornment: <LocalPhoneIcon color="secondary" />,
          conditionedBy: "shipping.shippingEqualsBasic",
          onConditionChange: createMirrorHandler("shipping.phone", "basic.phone"),
        },
        line1: {
          label: "Dirección (Linea 1)",
          errorCheck: (value) => value?.length >= 20,
          helperText: "Incluir todos los detalles posibles, incluidas referencias.",
          minRows: 3,
          adornment: <HomeIcon color="secondary" />,
          width: 12,
          conditionedBy: "shipping.shippingEqualsBasic",
          onConditionChange: createMirrorHandler("shipping.line1", "basic.line1"),
        },
        line2: {
          label: "Dirección (Linea 2)",
          errorCheck: (value) => value?.length >= 20,
          helperText: "Incluir todos los detalles posibles, incluidas referencias.",
          minRows: 3,
          adornment: <HomeIcon color="secondary" />,
          width: 12,
          conditionedBy: "shipping.shippingEqualsBasic",
          onConditionChange: createMirrorHandler("shipping.line2", "basic.line2"),
        },
        city: {
          label: "Ciudad",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          width: 4,
          conditionedBy: "shipping.shippingEqualsBasic",
          onConditionChange: createMirrorHandler("shipping.city", "basic.city"),
        },
        state: {
          label: "Estado",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          width: 4,
          conditionedBy: "shipping.shippingEqualsBasic",
          onConditionChange: createMirrorHandler("shipping.state", "basic.state"),
        },
        country: {
          label: "País",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          width: 4,
          conditionedBy: "shipping.shippingEqualsBasic",
          onConditionChange: createMirrorHandler("shipping.country", "basic.country"),
        },
        zipCode: {
          label: "Código Postal",
          errorCheck: (value) => /^\d{5}$/.test(value),
          helperText: "Formato no válido.",
          width: 4,
          conditionedBy: "shipping.shippingEqualsBasic",
          onConditionChange: createMirrorHandler("shipping.zipCode", "basic.zipCode"),
        },
        reference: {
          label: "Referencia",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          width: 4,
          conditionedBy: "shipping.shippingEqualsBasic",
          onConditionChange: createMirrorHandler("shipping.reference", "basic.reference"),
        },
        ShippingMethod: {
          label: "Método de Entrega",
          type: "dropdown",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          options: shippingMethods?.map((method) => method.name) || [],
          actionType: "SET_SHIPPING_DETAILS",
          renderKey: "shipping", 
          dataKey: "shipping", 
        },
        date: {
          label: "Fecha de Entrega",
          type: "date",
          errorCheck: (value) => value && !isNaN(Date.parse(value)),
          helperText: "Ingrese una fecha válida.",
          actionType: "SET_SHIPPING_DETAILS",
          renderKey: "shipping", 
          dataKey: "shipping", 
        },
      },
      actionType: "SET_SHIPPING_DETAILS",
      defaultCheckbox: "shippingEqualsBasic",
      headerLabel: "Enviado a:",
      headerValue: ["name", "lastName"],
      additionalFieldsPosition: "start",
    },
    billing: {
      title: "Datos de Facturación",
      fieldsTitle: "Dirección de Facturación",
      fields: {
        billingEqualsBasic: {
          label: "Igual a datos básicos",
          type: "checkbox",
          defaultValue: true,
          width: 12,
        },
        name: {
          label: "Nombre",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          conditionedBy: "billing.billingEqualsBasic",
          onConditionChange: createMirrorHandler("billing.name", "basic.name"),
        },
        lastName: {
          label: "Apellido",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          conditionedBy: "billing.billingEqualsBasic",
          onConditionChange: createMirrorHandler("billing.lastName", "basic.lastName"),
        },
        companyName: {
          label: "Razón Social",
          helperText: "Formato no válido.",
          required: false,
        },
        id: {
          label: "Cédula o RIF",
          errorCheck: (value, data) => {
            return data && data.companyName ? /^J-\d{8}-\d$/.test(value) : /^(?:[VEJ]-?)?\d{7,8}$/.test(value);
          },
          helperText:
            "Debe ser 12345678, V-12345679, E-12345679, o exactamente J-00012345-6 si es persona jurídica.",
          conditionedBy: "billing.billingEqualsBasic",
          onConditionChange: createMirrorHandler("billing.id", "basic.id"),
        },
        email: {
          label: "Correo",
          errorCheck: (value) => /\S+@\S+\.\S+/.test(value),
          helperText: "Formato no válido.",
          adornment: <EmailIcon color="secondary" />,
          conditionedBy: "billing.billingEqualsBasic",
          onConditionChange: createMirrorHandler("billing.email", "basic.email"),
        },
        phone: {
          label: "Teléfono",
          errorCheck: (value) => /^[0-9]{10,14}$/.test(value),
          helperText: "ej: 584141234567 ó +584141234567 ó 04143201028",
          adornment: <LocalPhoneIcon color="secondary" />,
          conditionedBy: "billing.billingEqualsBasic",
          onConditionChange: createMirrorHandler("billing.phone", "basic.phone"),
        },
        line1: {
          label: "Dirección (Linea 1)",
          errorCheck: (value) => value?.length >= 20,
          helperText: "Incluir todos los detalles posibles, incluidas referencias.",
          minRows: 3,
          adornment: <HomeIcon color="secondary" />,
          width: 12,
          conditionedBy: "billing.billingEqualsBasic",
          onConditionChange: createMirrorHandler("billing.line1", "basic.line1"),
        },
        line2: {
          label: "Dirección (Linea 2)",
          errorCheck: (value) => value?.length >= 20,
          helperText: "Incluir todos los detalles posibles, incluidas referencias.",
          minRows: 3,
          adornment: <HomeIcon color="secondary" />,
          width: 12,
          conditionedBy: "billing.billingEqualsBasic",
          onConditionChange: createMirrorHandler("billing.line2", "basic.line2"),
        },
        city: {
          label: "Ciudad",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          width: 4,
          conditionedBy: "billing.billingEqualsBasic",
          onConditionChange: createMirrorHandler("billing.city", "basic.city"),
        },
        state: {
          label: "Estado",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          width: 4,
          conditionedBy: "billing.billingEqualsBasic",
          onConditionChange: createMirrorHandler("billing.state", "basic.state"),
        },
        country: {
          label: "País",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          width: 4,
          conditionedBy: "billing.billingEqualsBasic",
          onConditionChange: createMirrorHandler("billing.country", "basic.country"),
        },
        zipCode: {
          label: "Código Postal",
          errorCheck: (value) => /^\d{4}$/.test(value),
          helperText: "Formato no válido.",
          width: 4,
          conditionedBy: "billing.billingEqualsBasic",
          onConditionChange: createMirrorHandler("billing.zipCode", "basic.zipCode"),
        },
        reference: {
          label: "Referencia",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          width: 4,
          conditionedBy: "billing.billingEqualsBasic",
          onConditionChange: createMirrorHandler("billing.reference", "basic.reference"),
        },
        paymentMethod: {
          label: "Método de Pago",
          type: "dropdown",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          options: paymentMethods?.map((method) => method.name) || [],
          actionType: "SET_PAYMENT_METHOD",
          renderKey: "billing", 
          dataKey: "billing",
        },
      },
      actionType: "SET_BILLING_DETAILS",
      defaultCheckbox: "billingEqualsBasic",
      headerLabel: "Facturado con:",
      headerValue: ["paymentMethod"],
    },
    general: {
      title: "Detalles de la Orden",
      fields: {
        observations: {
          label: "Observaciones",
          helperText: "Incluir todos los detalles posibles.",
          actionType: "SET_OBSERVATIONS",
          multiline: true,
          minRows: 3,
          required: false,
        },
        seller: {
          label: "Vendedor",
          type: "dropdown",
          errorCheck: (value) => value?.length >= 2,
          helperText: "Formato no válido.",
          options: sellers || [],
          actionType: "SET_SELLER",
          tooltip: "¿Alguno de nuestros asesores te ayudó en el proceso de compra?",
          required: false,
        },
      },
    }
  };

  return formConfig;
}
