name: build

on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 15.8.0
      uses: actions/setup-node@v1
      with:
        node-version: '15.8.0'
    - name: Install npm and run unittest
      run: |
        npm install
      env:
        CI: true
    - name: create env file
      run: |
        touch .env
        echo "REACT_APP_CLOUD_NAME=${{ secrets.REACT_APP_CLOUD_NAME }}" >> .env
        echo "REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}" >> .env
    - name: Publish to Github Packages Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: capuzr/prixelart-frontend/frontend
        registry: docker.pkg.github.com
        username: ${{ secrets.GIT_USERNAME }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: dockerfile.prod
        tags: latest
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
      env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.DIGITAL_OCEAN_IP }}
        username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
        password: ${{ secrets.DIGITAL_OCEAN_PASSWORD }}
        envs: GIT_USERNAME, GITHUB_TOKEN
        script: |
          docker stop $(docker ps -a -q)
          docker login docker.pkg.github.com -u $GIT_USERNAME -p $GITHUB_TOKEN
          docker pull docker.pkg.github.com/capuzr/prixelart-frontend/frontend:latest
          docker run -itd -p 80:80 docker.pkg.github.com/capuzr/prixelart-frontend/frontend:latest
